### ISSUE TITLE
Create proper tags new new docker container versions

### ISSUE THREAD

**Issue by svenmueller** [commercetools/mongo-metrics-reporter#6]
Only having `latest` is not enough since using the latest version might not work with the current used influxdb version anymore.

**Comment by OlegIlyenko** [comment]
Here we go, I released v2.0 and from now on will use proper versioning (with proper git and docker tags):

https://github.com/commercetools/mongo-metrics-reporter/releases/tag/v2.0
https://hub.docker.com/r/tenshi/mongo-metrics-reporter/tags/
