### ISSUE TITLE
What happens if primary changes after re-election?

### ISSUE THREAD

**Issue by svenmueller** [commercetools/mongo-metrics-reporter#7]
Hi,

I'm just wondering what happens if a re-election happens and the primary changes. Is the metrics-reporter still capable of gathering metrics from the secondary node?

Thanks!

**Comment by OlegIlyenko** [comment]
Yes, reporter will continue to work and send secondary's metrics. In fact it already happened a few times. 

Ideally reporter should be able to detect primary changes and adopt itself. Secondary stats are not very useful (at least not as useful as primary's)

**Comment by svenmueller** [comment]
Thx! Yep, that's true. Actually it would be really nice if the reporter could send stats for all nodes in the cluster :)

Thx a lot for your work!
